// Typed access to items.json, the build-time bake of the Destiny manifest.
//
// items.json is generated by scripts/build-data.mjs, which resolves ONLY the
// curated list and verifies every hash's name against the expected item name
// before writing anything. The site never downloads the manifest at runtime;
// the game is frozen at 9.7.0.4, so neither is a compromise.

import raw from './items.json';
import type { ArmorSlot, GuardianClass, StatName, WeaponSlot } from '../types';

export interface BakedItem {
  name: string;
  /** Every manifest version of this item. Owning any of them counts. */
  hashes: number[];
  collectibleHashes: number[];
  primaryHash: number;
  icon: string;
  kind: 'weapon' | 'armor';
  slot: WeaponSlot | ArmorSlot;
  /** 0 Titan, 1 Hunter, 2 Warlock, 3 any. */
  classType: number;
  tierType: number;
  itemTypeDisplayName: string;
  ammoType: number;
  damageType: number;
  /**
   * The intrinsic frame, resolved from the manifest. null when the weapon
   * rolls its intrinsic (Ergo Sum) or none resolved; the champion note says
   * so honestly instead of guessing.
   */
  frame: string | null;
  aliases: string[];
}

interface BakedData {
  manifestVersion: string;
  generated: string;
  note: string;
  statHashes: Record<StatName, number>;
  cipher: { name: string; hash: number };
  emptyCatalystSocket: number[];
  perks: Record<string, number[]>;
  catalysts: Record<string, { name: string; hashes: number[] }>;
  items: Record<string, BakedItem>;
}

const data = raw as unknown as BakedData;

export const MANIFEST_VERSION: string = data.manifestVersion;
export const BAKED_ITEMS: Record<string, BakedItem> = data.items;
export const STAT_HASHES: Record<StatName, number> = data.statHashes;
export const CIPHER_HASH: number = data.cipher.hash;
export const PERK_HASHES: Record<string, number[]> = data.perks;
export const CATALYST_HASHES: Record<string, { name: string; hashes: number[] }> = data.catalysts;
export const EMPTY_CATALYST_HASHES: number[] = data.emptyCatalystSocket;

export const ITEM_ID_BY_HASH: ReadonlyMap<number, string> = (() => {
  const map = new Map<number, string>();
  for (const [id, item] of Object.entries(data.items)) {
    for (const hash of item.hashes) map.set(hash, id);
  }
  return map;
})();

export const ITEM_ID_BY_COLLECTIBLE: ReadonlyMap<number, string> = (() => {
  const map = new Map<number, string>();
  for (const [id, item] of Object.entries(data.items)) {
    for (const hash of item.collectibleHashes) map.set(hash, id);
  }
  return map;
})();

const WEAPON_SLOT_LABELS: Record<string, string> = {
  kinetic: 'Kinetic',
  energy: 'Energy',
  power: 'Power',
  helmet: 'Helmet',
  gauntlets: 'Gauntlets',
  chest: 'Chest',
  legs: 'Legs',
  classitem: 'Class item'
};

export function slotLabel(slot: string): string {
  return WEAPON_SLOT_LABELS[slot] ?? slot;
}

export function bakedItem(id: string): BakedItem | null {
  return data.items[id] ?? null;
}

export function isArmorForClass(id: string, classType: GuardianClass): boolean {
  const item = data.items[id];
  return !!item && item.kind === 'armor' && item.classType === classType;
}

/** Full bungie.net URL for an icon path out of the manifest. */
export function iconUrl(path: string): string {
  if (!path) return '';
  if (path.startsWith('http')) return path;
  return 'https://www.bungie.net' + path;
}
